<?php
/**
 * @file provides kinds of UI enhansment widget.
 *
 * @URL https://www.drupal.org/docs/7/core/modules/image/working-with-images
 * @URL https://www.drupal.org/node/465230 Posting video from mobile.
 * @URL http://git.blivesta.com/drawer/package-managers/
 * @URL https://github.com/cubiq/iscroll#configuring-the-iscroll
 * @URL https://www.drupal.org/project/drupal/issues/2753457
 * @URL https://www.antimath.info/css/change-throbber-in-drupal-7/
 * @URL https://zhuanlan.zhihu.com/p/26430952 WeUI Uploader with Vue.JS
 * @see https://www.drupal.org/docs/7/api/javascript-api/ajax-forms-in-drupal-7
 * @see https://api.drupal.org/api/drupal/includes%21ajax.inc/group/ajax/7.x
 */

/**
 * Human name.
 */
define('MOHA_UI', 'Moha UI');

/**
 * Machine name.
 */
define('__MOHA_UI', 'moha_ui');

/**
 * sites/all/modules/custom/moha/modules/moha_ui.
 */
define('MOHA_UI__PATH', drupal_get_path('module', __MOHA_UI));

/**
 * /sites/all/modules/custom/moha/modules/moha_ui.
 */
define('__MOHA_UI__PATH', base_path() . MOHA_UI__PATH);

/**
 * Module variables name.
 */
define('MOHA_UI__VARIABLES', __MOHA_UI. '__variables');

/**
 * Implements hook_library().
 */
function moha_ui_library() {
  $libraries[__MOHA_UI] = array(
    'title' => MOHA_UI,
    'website' => 'https://www.moha.online/',
    'version' => '1.0',
    'js' => array(
      MOHA_UI__PATH . '/libs/weui.js/dist/weui.js' => array(),
      MOHA_UI__PATH . '/libs/jquery.rating-stars/dist/js/jquery.rating-stars.js' => array(),
    ),
    'css' => array(
      MOHA_UI__PATH . '/libs/weui/dist/style/weui.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      MOHA_UI__PATH . '/libs/font-awesome/css/font-awesome.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      MOHA_UI__PATH . '/css/moha_ui.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_libraries_info().
 */
function moha_ui_libraries_info() {

  $libraries[__MOHA_UI] = array(
    'name' => MOHA_UI,
    'library path' => MOHA_UI__PATH,
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'libs/weui.js/dist/weui.js',
      ),
      'css' => array(
        'libs/weui/dist/style/weui.css',
        'libs/font-awesome/css/font-awesome.css',
        'css/moha_ui.css',
      ),
      'php' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_element_info().
 *
 * @see https://www.drupal.org/node/169815
 */
function moha_ui_element_info() {

  $elements = array(
    /* Element: Moha UI - Rating. */
    'moha_ui_rating' => array(
      /* Element carries a value. */
      '#input' => TRUE,
      '#theme' => array('moha_ui_rating'),
    ),

  );

  return $elements;
}

/**
 * Implements hook_theme().
 */
function moha_ui_theme($existing, $type, $theme, $path) {
  $templates = array(
    'moha_ui_rating' => array(
      'template' => 'elements/moha_ui_rating',
      'rent element' => 'element',
    ),
  );

  return $templates;
}

/**
 * Implements hook_field_info().
 *
 * @see https://api.drupal.org/api/drupal/modules!field!field.module/group/field/7.x
 */
function moha_ui_field_info() {

}

/**
 * Implements hook_field_widget_info().
 */
function moha_ui_field_widget_info() {

//  .ajax-progress-throbber
//  .ajax-progress-throbber .message
//  .ajax-progress-throbber .throbber

  $widgets = array(
    'moha_ui_image_mobile_uploader' => array(
      'label' => t('Moha UI: Image Mobile Uploader'),
      'field types' => array('image'),
      'settings' => array(
        /** @see https://www.antimath.info/css/change-throbber-in-drupal-7/ */
        'progress_indicator' => 'toast',
        'preview_image_style' => 'thumbnail',
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_form().
 */
function moha_ui_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  libraries_load(__MOHA_UI);
  drupal_add_js(MOHA_UI__PATH.'/js/moha_ui.js');

  $widget = array(
    '#type' => 'managed_file',
    '#process' => array('moha_ui_file_process'),
    '#value_callback' => 'moha_ui_file_value',
  );

  $element += $widget;

  $form['moha_ui_file_values'] = array(
    '#type' => 'hidden',
    '#value' => NULL,
  );

  $form['moha_ui_field_name'] = array(
    '#type' => 'hidden',
    '#value' => $field['field_name'],
  );

  $form['#submit'][] = 'moha_ui_field_widget_submit';

  return $element;
}

/**
 * Implements hook_field_formatter_info().
 */
function moha_ui_field_formatter_info() {

}

/**
 * Implements hook_webform_component_info().
 */
function moha_ui_webform_component_info() {
  /* Only 16 chars are allowed as Webform component machine name. */
  $components['moha_ui_rating'] = array(
    'label' => t('Moha UI - Rating'),
    'description' => t('Provides Rating field for WebForm.'),
    'features' => array(
      // This component includes an analysis callback. Defaults to TRUE.
      'analysis' => TRUE,

      // Add content to CSV downloads. Defaults to TRUE.
      'csv' => TRUE,

      // This component supports default values. Defaults to TRUE.
      'default_value' => FALSE,

      // This component supports a description field. Defaults to TRUE.
      'description' => FALSE,

      // Show this component in e-mailed submissions. Defaults to TRUE.
      'email' => TRUE,

      // Allow this component to be used as an e-mail FROM or TO address.
      // Defaults to FALSE.
      'email_address' => FALSE,

      // Allow this component to be used as an e-mail SUBJECT or FROM name.
      // Defaults to FALSE.
      'email_name' => TRUE,

      // This component may be toggled as required or not. Defaults to TRUE.
      'required' => TRUE,

      // This component supports a title attribute. Defaults to TRUE.
      'title' => TRUE,

      // This component has a title that can be toggled as displayed or not.
      'title_display' => TRUE,

      // This component has a title that can be displayed inline.
      'title_inline' => TRUE,

      // If this component can be used as a conditional SOURCE. All components
      // may always be displayed conditionally, regardless of this setting.
      // Defaults to TRUE.
      'conditional' => TRUE,

      // If this component allows other components to be grouped within it
      // (like a fieldset or tabs). Defaults to FALSE.
      'group' => FALSE,

      // If this component can be used for SPAM analysis.
      'spam_analysis' => FALSE,

      // If this component saves a file that can be used as an e-mail
      // attachment. Defaults to FALSE.
      'attachment' => FALSE,

      // If this component reflects a time range and should use labels such as
      // "Before" and "After" when exposed as filters in Views module.
      'views_range' => FALSE,

      // Set this to FALSE if this component cannot be used as a private
      // component. If this is not FALSE, in your implementation of
      // _webform_defaults_COMPONENT(), set ['extra']['private'] property to
      // TRUE or FALSE.
      'private' => FALSE,
    ),

    // Specify the conditional behaviour of this component.
    // Examples are 'string', 'date', 'time', 'numeric', 'select'.
    // Defaults to 'string'.
    'conditional_type' => 'numeric',

    'file' => 'webform/components/moha_ui_rating.inc',
  );

  return $components;
}

function moha_ui_field_widget_submit($form, &$form_state) {

  $field_name = $form_state['values']['moha_ui_field_name'];
  $language = $form[$field_name]['#language'];
  //$file_directory = $form_state['field'][$field_name][$language]['instance']['settings']['file_directory'];
  //$file_extensions = $form_state['field'][$field_name][$language]['instance']['settings']['file_extensions'];


  if($form_state['input']['moha_ui_file_values']) {
    $file_values = explode(',,',$form_state['input']['moha_ui_file_values']);
    $fids = array();
    foreach($file_values as $content){
      $file_contents = file_get_contents($content);
      $file = file_save_data($file_contents);
      $fids[] =  $file->fid;
    }
    if(!empty($fids)){
      if(empty($form_state['input'][$field_name][$language]['fid'])){
        $form_state['moha_ui_fids'] = $fids;
      } else {
        $old_fids = explode(' ', $form_state['input'][$field_name][$language]['fid']);
        $form_state['moha_ui_insert_fids'] = $fids;
        $form_state['moha_ui_fids'] = array_merge($old_fids, $fids);
      }
      $form_state['rebuild'] = true;
    }
  }

}



function moha_ui_file_value(&$element, $input = FALSE, $form_state = NULL) {

  $return['fid'] = array();

  if ($input !== FALSE) {
    if(isset($form_state['moha_ui_fids'])){
      $entity_type = $element['#entity_type'];
      $entity = $element['#entity'];
      $field_name = $element['#field_name'];
      $langcode = $element['#language'];
      $field = $form_state['field'][$field_name][$langcode]['instance'];
      $instance = $form_state['field'][$field_name][$langcode]['instance'];

      $items = array();
      foreach($form_state['moha_ui_fids'] as $key => $fid ){
        $items[$key] = array('fid'=> $fid);
        $entity->$field_name[$langcode][$key]['fid'] = $fid;
      }
//      if(empty($form_state['input'][$field_name][$langcode]['fid'])){
//        file_field_insert($entity_type, $entity, $field, $instance, $langcode,$items);
//      } else {
//        list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
//        // Add a new usage of each uploaded file.
//        foreach ($items as $item) {
//          if(in_array($item['fid'], $form_state['moha_ui_insert_fids'])){
//            $file = (object) $item;
//            file_usage_add($file, 'file', $entity_type, $id);
//          }
//        }
//      }

      //save field value record
      $info = field_info_field($field_name);
      $fields = array($info['id']);
      field_sql_storage_field_storage_write($entity_type, $entity, 'update', $fields);
      $return = $items;
      drupal_goto($form_state['redirect']);
    }
  } else {
    $field_name = $element['#field_name'];
    if(isset($element['#entity']->$field_name)){
      $field_values = $element['#entity']->$field_name;
      //$return = $field_values[$element['#language']];
      foreach($field_values[$element['#language']] as $value){
        $return['fid'][] = $value['fid'];
      }
    }

  }

  return $return;
}


function moha_ui_file_process($element, &$form_state, $form) {

  $original_id = $element['#id'];
  $element['#id'] .= '-upload';
  $fid = isset($element['#value']['fid']) ? $element['#value']['fid'] : 0;

  $element['fid'] = array(
    '#type' => 'hidden',
    '#value' => $fid,
  );

  $image_display='';
  if($fid){
    foreach($fid as $item_fid){
      $file = file_load($item_fid);
      $fileUrl = file_create_url($file->uri);
      $image_display .= '<li class="weui-uploader__file" style="background-image:url(' . $fileUrl . '");></li>';
    }
  }

  $element['markup'] = array(
    '#markup' => '
      <div class="weui-cells weui-cells_form" id="uploaderCustom">
        <div class="weui-uploader__bd">
          <ul class="weui-uploader__files" id="uploaderCustomFiles">' . $image_display . '</ul>
          <div class="weui-uploader__input-box">
            <input id="uploaderCustomInput" class="weui-uploader__input" type="file" accept="image/*"  multiple="">
          </div>
        </div>
      </div>',
  );

  return $element;
}


