<?php
/**
 * @file provides kinds of UI enhansment widget.
 *
 * @URL https://www.drupal.org/docs/7/core/modules/image/working-with-images
 * @URL https://www.drupal.org/node/465230 Posting video from mobile.
 * @URL http://git.blivesta.com/drawer/package-managers/
 * @URL https://github.com/cubiq/iscroll#configuring-the-iscroll
 * @URL https://www.drupal.org/project/drupal/issues/2753457
 * @URL https://www.antimath.info/css/change-throbber-in-drupal-7/
 * @URL https://zhuanlan.zhihu.com/p/26430952 WeUI Uploader with Vue.JS
 * @see https://www.drupal.org/docs/7/api/javascript-api/ajax-forms-in-drupal-7
 * @see https://api.drupal.org/api/drupal/includes%21ajax.inc/group/ajax/7.x
 */

/**
 * Human name.
 */
define('MOHA_UI', 'Moha UI');

/**
 * Machine name.
 */
define('__MOHA_UI', 'moha_ui');

/**
 * sites/all/modules/custom/moha/modules/moha_ui.
 */
define('MOHA_UI__PATH', drupal_get_path('module', __MOHA_UI));

/**
 * /sites/all/modules/custom/moha/modules/moha_ui.
 */
define('__MOHA_UI__PATH', base_path() . MOHA_UI__PATH);

/**
 * Module variables name.
 */
define('MOHA_UI__VARIABLES', __MOHA_UI. '__variables');

/**
 * Implements hook_library().
 */
function moha_ui_library() {
  $libraries[__MOHA_UI] = array(
    'title' => MOHA_UI,
    'website' => 'https://www.moha.online/',
    'version' => '1.0',
    'js' => array(
      MOHA_UI__PATH . '/libs/weui.js/dist/weui.js' => array(),
      MOHA_UI__PATH . '/libs/jquery.rating-stars/dist/js/jquery.rating-stars.js' => array(),
    ),
    'css' => array(
      MOHA_UI__PATH . '/libs/weui/dist/style/weui.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      MOHA_UI__PATH . '/libs/font-awesome/css/font-awesome.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      MOHA_UI__PATH . '/css/moha_ui.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_libraries_info().
 */
function moha_ui_libraries_info() {

  $libraries[__MOHA_UI] = array(
    'name' => MOHA_UI,
    'library path' => MOHA_UI__PATH,
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'libs/weui.js/dist/weui.js',
      ),
      'css' => array(
        'libs/weui/dist/style/weui.css',
        'libs/font-awesome/css/font-awesome.css',
        'css/moha_ui.css',
      ),
      'php' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_element_info().
 *
 * @see https://www.drupal.org/node/169815
 */
function moha_ui_element_info() {

  $elements = array(
    /* Element: Moha UI - Rating. */
    'moha_ui_rating' => array(
      /* Element carries a value. */
      '#input' => TRUE,
      '#theme' => array('moha_ui_rating'),
    ),

  );

  return $elements;
}

/**
 * Implements hook_theme().
 */
function moha_ui_theme($existing, $type, $theme, $path) {
  $templates = array(
    'moha_ui_rating' => array(
      'template' => 'elements/moha_ui_rating',
      'rent element' => 'element',
    ),
  );

  return $templates;
}

/**
 * Implements hook_field_info().
 *
 * @see https://api.drupal.org/api/drupal/modules!field!field.module/group/field/7.x
 */
function moha_ui_field_info() {

}

/**
 * Implements hook_field_widget_info().
 */
function moha_ui_field_widget_info() {

//  .ajax-progress-throbber
//  .ajax-progress-throbber .message
//  .ajax-progress-throbber .throbber

  $widgets = array(
    'moha_ui_image_mobile_uploader' => array(
      'label' => t('Moha UI: Image Mobile Uploader'),
      'field types' => array('image'),
      'settings' => array(
        /** @see https://www.antimath.info/css/change-throbber-in-drupal-7/ */
        'progress_indicator' => 'toast',
        'preview_image_style' => 'thumbnail',
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_form().
 */
function moha_ui_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  libraries_load(__MOHA_UI);
  drupal_add_js(MOHA_UI__PATH.'/js/moha_ui.js');
  //dpm($delta, 'delta');
  //dpm($items, 'items');

  $defaults = array(
    'fid' => 0,
    'display' => !empty($field['settings']['display_default']),
    'description' => '',
  );

  $default_items = array();
  for($i = 0; $i < $field['cardinality']; $i++){
    $default_items[$i] = $defaults;
  }

  // Load the items for form rebuilds from the field state as they might not be
  // in $form_state['values'] because of validation limitations. Also, they are
  // only passed in as $items when editing existing entities.
  $field_state = field_form_get_state($element['#field_parents'], $field['field_name'], $langcode, $form_state);
  if (isset($field_state['items'])) {
    $items = $field_state['items'];
  }

  // Essentially we use the managed_file type, extended with some enhancements.
  $element_info = element_info('managed_file');
  $widget = array(
    '#type' => 'managed_file',
    '#upload_location' => file_field_widget_uri($field, $instance),
    '#upload_validators' => file_field_widget_upload_validators($field, $instance),
    '#value_callback' => 'moha_ui_field_widget_value',
    '#process' => array_merge($element_info['#process'],array('image_field_widget_process','moha_ui_file_process')),
    '#progress_indicator' => $instance['widget']['settings']['progress_indicator'],
    // Allows this field to return an array instead of a single value.
    '#extended' => TRUE,
  );
  $element += $widget;

  $elements['moha_ui_preview'] = array(
    '#markup' => '<div style="overflow:auto;"><ul id="moha_ui_preview"></ul></div>',
  );

  if ($field['cardinality'] == 1) {
    // Set the default value.
    $element['#default_value'] = !empty($items) ? $items[0] : $defaults;
    // If there's only one field, return it as delta 0.
    if (empty($element['#default_value']['fid'])) {
      $element['#description'] = theme('file_upload_help', array('description' => $element['#description'], 'upload_validators' => $element['#upload_validators']));
    }
    $elements = array($element);
  }
  else {
    if(empty($items)){
      foreach ($default_items as $item) {
        $element['#delta'] = $delta;
        $elements[$delta] = $element;
        $elements[$delta]['#default_value'] = $item;
        $elements[$delta]['#weight'] = $delta;
        $elements[$delta]['#description'] = theme('file_upload_help', array('description' => $element['#description'], 'upload_validators' => $element['#upload_validators']));
        $delta++;
      }
    } else {
      // If there are multiple values, add an element for each existing one.
      foreach ($items as $item) {
        $element['#delta'] = $delta;
        $elements[$delta] = $element;
        $elements[$delta]['#default_value'] = $item;
        $elements[$delta]['#weight'] = $delta;
        $delta++;
      }
    }


    if (($field['cardinality'] == FIELD_CARDINALITY_UNLIMITED || $delta < $field['cardinality']) && empty($form_state['programmed'])) {
      $element['#delta'] = $delta;
      $elements[$delta] = $element;
      $elements[$delta]['#default_value'] = $defaults;
      $elements[$delta]['#weight'] = $delta;
      //$elements[$delta]['#required'] = ($element['#required'] && $delta == 0);
    }
    // The group of elements all-together need some extra functionality
    // after building up the full list (like draggable table rows).
    $elements['#file_upload_delta'] = $delta;
    //$elements['#theme'] = 'file_widget_multiple';
    $elements['#theme_wrappers'] = array('fieldset');
    //$elements['#process'] = array('file_field_widget_process_multiple');
    $elements['#title'] = $element['#title'];
    $elements['#description'] = $element['#description'];
    $elements['#field_name'] = $element['#field_name'];
    $elements['#language'] = $element['#language'];
    //$elements['#display_field'] = $field['settings']['display_field'];

    // Add some properties that will eventually be added to the file upload
    // field. These are added here so that they may be referenced easily through
    // a hook_form_alter().
    $elements['#file_upload_title'] = t('Add a new file');
    $elements['#file_upload_description'] = theme('file_upload_help', array('description' => '', 'upload_validators' => $elements[0]['#upload_validators']));

  }

  return $elements;

}

/**
 * Implements hook_field_formatter_info().
 */
function moha_ui_field_formatter_info() {

}

/**
 * Implements hook_webform_component_info().
 */
function moha_ui_webform_component_info() {
  /* Only 16 chars are allowed as Webform component machine name. */
  $components['moha_ui_rating'] = array(
    'label' => t('Moha UI - Rating'),
    'description' => t('Provides Rating field for WebForm.'),
    'features' => array(
      // This component includes an analysis callback. Defaults to TRUE.
      'analysis' => TRUE,

      // Add content to CSV downloads. Defaults to TRUE.
      'csv' => TRUE,

      // This component supports default values. Defaults to TRUE.
      'default_value' => FALSE,

      // This component supports a description field. Defaults to TRUE.
      'description' => FALSE,

      // Show this component in e-mailed submissions. Defaults to TRUE.
      'email' => TRUE,

      // Allow this component to be used as an e-mail FROM or TO address.
      // Defaults to FALSE.
      'email_address' => FALSE,

      // Allow this component to be used as an e-mail SUBJECT or FROM name.
      // Defaults to FALSE.
      'email_name' => TRUE,

      // This component may be toggled as required or not. Defaults to TRUE.
      'required' => TRUE,

      // This component supports a title attribute. Defaults to TRUE.
      'title' => TRUE,

      // This component has a title that can be toggled as displayed or not.
      'title_display' => TRUE,

      // This component has a title that can be displayed inline.
      'title_inline' => TRUE,

      // If this component can be used as a conditional SOURCE. All components
      // may always be displayed conditionally, regardless of this setting.
      // Defaults to TRUE.
      'conditional' => TRUE,

      // If this component allows other components to be grouped within it
      // (like a fieldset or tabs). Defaults to FALSE.
      'group' => FALSE,

      // If this component can be used for SPAM analysis.
      'spam_analysis' => FALSE,

      // If this component saves a file that can be used as an e-mail
      // attachment. Defaults to FALSE.
      'attachment' => FALSE,

      // If this component reflects a time range and should use labels such as
      // "Before" and "After" when exposed as filters in Views module.
      'views_range' => FALSE,

      // Set this to FALSE if this component cannot be used as a private
      // component. If this is not FALSE, in your implementation of
      // _webform_defaults_COMPONENT(), set ['extra']['private'] property to
      // TRUE or FALSE.
      'private' => FALSE,
    ),

    // Specify the conditional behaviour of this component.
    // Examples are 'string', 'date', 'time', 'numeric', 'select'.
    // Defaults to 'string'.
    'conditional_type' => 'numeric',

    'file' => 'webform/components/moha_ui_rating.inc',
  );

  return $components;
}

function moha_ui_field_widget_value($element, $input = FALSE, $form_state = NULL) {
  $return = file_field_widget_value($element, $input, $form_state);
  return $return;
}


function moha_ui_file_process($element, $form_state, $form) {
//  if($element['#delta']== 0){
//    dpm($element, 'before');
//  }


 if($element['fid']['#value'] == 0){
   $element['upload']['#prefix'] = '<div class="weui-cells weui-cells_form" id="uploaderCustom">
     <div class="weui-uploader__bd">
     <div class="weui-uploader__input-box">';
   $element['upload']['#suffix'] = '</div></div></div>';
   $element['upload']['#attributes'] = array('class' => array('weui-uploader__input'));
   $element['upload_button']['#type'] = 'hidden';
 }


//  if($element['#delta']== 0){
//    dpm($element, 'after');
//  }

  return $element;
}


